import { LoginModal } from './LoginModal';
import { LoginTitle } from './LoginTitle';
import * as S from './styles';
export const LoginComponent = () => {
  return (
    <S.Container>
      <LoginTitle />
      <LoginModal />
      <S.BubblesContainer>
        <S.Bubbles2
          speed={30}
          left={2}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles2
          speed={45}
          left={4}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles2
          speed={25}
          left={6}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles2
          speed={48}
          left={8}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles2
          speed={78}
          left={10}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles2
          speed={65}
          left={12}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles2
          speed={48}
          left={14}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles2
          speed={35}
          left={16}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles2
          speed={48}
          left={18}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles2
          speed={36}
          left={20}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />

        <S.Bubbles
          speed={36}
          left={80}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles
          speed={48}
          left={82}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles
          speed={35}
          left={84}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles
          speed={48}
          left={86}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles
          speed={65}
          left={88}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles
          speed={78}
          left={90}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles
          speed={48}
          left={92}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles
          speed={25}
          left={94}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
        <S.Bubbles
          speed={45}
          left={96}
          color1={'#4fc3dc'}
          color2={'#4fc3dc44'}
        />
        <S.Bubbles
          speed={30}
          left={98}
          color1={'#ff2d75'}
          color2={'#ff2d7544'}
        />
      </S.BubblesContainer>
    </S.Container>
  );
};
